[workspace]
resolver = "3"
members = [
    "hfendpoints",
    "hfendpoints-binding-python",
    "hfendpoints-transports",
    "hfendpoints-transports-axum"
]

[workspace.dependencies]
pyo3 = { version = "0.24.0", features = ["abi3-py312"] }
