[package]
name = "hfendpoints-binding-python"
version = "0.1.0"
edition = "2024"

[dependencies]
pyo3.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"], optional = true }

[features]
default = []
tokio = ["dep:tokio"]