[package]
name = "hfendpoints-transports"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { version = "1.0" }
pyo3 = { workspace = true, optional = true }


[features]
default = []
python = ["pyo3"]