[package]
name = "hfendpoints"
version = "0.1.0"
edition = "2024"

[dependencies]
hfendpoints-binding-python = { path = "../hfendpoints-binding-python", optional = true }
hfendpoints-transports = { path = "../hfendpoints-transports" }
hfendpoints-transports-axum = { path = "../hfendpoints-transports-axum" }
pyo3 = { workspace = true, optional = true, features = ["extension-module"] }
pyo3-log = { version = "0.12.2", optional = true }

[features]
default = []
python = ["pyo3", "pyo3-log", "hfendpoints-transports/python", "hfendpoints-transports-axum/python", "hfendpoints-binding-python"]